name: Phase7 Sign AAB

on:
  workflow_dispatch: # Allows manual triggering
  # push:
    # branches: [ main ] # Or your default branch - consider changing for release
    # tags:
      # - 'v*.*.*'      # Trigger on version tags like v1.0.0, v1.0.1

jobs:
  build_and_sign_release:
    name: Build Signed Release 7 AAB
    runs-on: ubuntu-latest
    # Optional: Condition to run only on manual dispatch or tags
    # if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # To get version name from git tag if you implement that later

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # THIS STEP IS KEPT AS IS, PER YOUR INSTRUCTION
      - name: Set up Android SDK
        run: |
          echo "ANDROID_SDK_ROOT=${HOME}/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=${HOME}/android-sdk" >> $GITHUB_ENV # Legacy
          SDK_CMD_TOOLS_PATH="${HOME}/android-sdk/cmdline-tools/latest/bin"
          SDK_PLATFORM_TOOLS_PATH="${HOME}/android-sdk/platform-tools"
          SDK_EMULATOR_PATH="${HOME}/android-sdk/emulator" # Included for completeness
          echo "$SDK_CMD_TOOLS_PATH" >> $GITHUB_PATH
          echo "$SDK_PLATFORM_TOOLS_PATH" >> $GITHUB_PATH
          echo "$SDK_EMULATOR_PATH" >> $GITHUB_PATH
          export PATH="$SDK_CMD_TOOLS_PATH:$SDK_PLATFORM_TOOLS_PATH:$SDK_EMULATOR_PATH:$PATH"
          mkdir -p ${HOME}/android-sdk/cmdline-tools
          CMDTOOLS_VERSION_ZIP="commandlinetools-linux-11076708_latest.zip"
          echo "Downloading Android Command-line Tools: ${CMDTOOLS_VERSION_ZIP}"
          wget --quiet "https://dl.google.com/android/repository/${CMDTOOLS_VERSION_ZIP}" -O cmdline-tools.zip
          echo "Unzipping Command-line Tools..."
          unzip -q cmdline-tools.zip -d ${HOME}/android-sdk/cmdline-tools
          mv ${HOME}/android-sdk/cmdline-tools/cmdline-tools ${HOME}/android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip
          echo "Command-line Tools installed to ${HOME}/android-sdk/cmdline-tools/latest"
          echo "Verifying sdkmanager..."
          which sdkmanager
          sdkmanager --version || echo "sdkmanager --version failed"
          echo "Accepting SDK licenses..."
          yes | sdkmanager --licenses > /dev/null || echo "Failed to accept licenses, retrying with --sdk_root"
          yes | sdkmanager --licenses --sdk_root="${ANDROID_HOME}" > /dev/null || echo "Failed to accept licenses with --sdk_root"
          echo "Installing SDK packages..."
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools" > /dev/null || echo "Failed to install SDK packages"
          echo "SDK Setup Complete. Installed packages:"
          sdkmanager --list_installed || echo "sdkmanager --list_installed failed"
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT || format('{0}/android-sdk', env.HOME) }}
                  
      # Step 1: Check if GOOGLE_SERVICES_JSON_BASE64 secret is set
      - name: Check for Google Services JSON Secret
        id: check_gservices_secret
        run: |
          if [ -n "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" ]; then
            echo "GSERVICES_JSON_SECRET_SET=true" >> $GITHUB_ENV
          else
            echo "GSERVICES_JSON_SECRET_SET=false" >> $GITHUB_ENV
          fi

      # Step 2: Decode google-services.json (uses the env var from above step)
      - name: Decode google-services.json
        if: env.GSERVICES_JSON_SECRET_SET == 'true'
        run: |
          echo "Decoding google-services.json..."
          mkdir -p ${{ github.workspace }}/app # Ensure app directory exists
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > ${{ github.workspace }}/app/google-services.json
          echo "google-services.json placed in app module root."
          # Verify file exists
          if [ -f "${{ github.workspace }}/app/google-services.json" ]; then
            echo "google-services.json created successfully."
          else
            echo "ERROR: google-services.json NOT created."
            # exit 1 # Optionally fail if not present and expected
          fi
          
      - name: Decode Keystore and Set Up Signing Variables
        run: |
          if [ -z "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" ] || \
             [ -z "${{ secrets.SIGNING_KEYSTORE_PASSWORD }}" ] || \
             [ -z "${{ secrets.SIGNING_KEY_ALIAS }}" ] || \
             [ -z "${{ secrets.SIGNING_KEY_PASSWORD }}" ]; then
            echo "::error::Required signing secrets are not set. Skipping keystore decoding and signing setup."
            exit 0 # Exit gracefully, allows other non-signing jobs to run if any, or just shows a clear message
          fi

          echo "Decoding keystore..."
          KEYSTORE_FILE_PATH_IN_RUNNER="${HOME}/signing_keystore.jks"
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > $KEYSTORE_FILE_PATH_IN_RUNNER
          
          if [ ! -f "$KEYSTORE_FILE_PATH_IN_RUNNER" ] || [ ! -s "$KEYSTORE_FILE_PATH_IN_RUNNER" ]; then
            echo "::error::Failed to decode keystore or keystore is empty."
            exit 1 # Fail the job if keystore is not created or is empty
          else
            echo "Keystore file created at $KEYSTORE_FILE_PATH_IN_RUNNER"
          fi

          echo "Setting up signing environment variables for Gradle..."
          echo "SIGNING_KEYSTORE_FILE_PATH=$KEYSTORE_FILE_PATH_IN_RUNNER" >> $GITHUB_ENV
          echo "SIGNING_KEYSTORE_PASSWORD_ENV=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_ALIAS_ENV=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_PASSWORD_ENV=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
          
          echo "Signing variables set."

      - name: Setup Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Signed Release AAB
        run: |
          echo "Starting Release Build..."
          ./gradlew bundleRelease
        env:
          # ANDROID_SDK_ROOT and ANDROID_HOME are already in GITHUB_ENV
          # The SIGNING_... variables are also set in GITHUB_ENV from the previous step
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Upload Release AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-aab
          path: app/build/outputs/apk/release/app-release.aab
          if-no-files-found: error
